### ISSUE TITLE
A. mellifera reference genome version 

### ISSUE THREAD

**Issue by burcudsr** [zhongw2/GeneTEFlow#2]
Hello,

I want to use GeneTEFlow pipeline for Apis mellifera. But A. mellifera latest genome version Amel_4.5 is not available in UCSC (version apiMel2 is available). Do you have any suggestions about alternative ways? 

Thanks in advance,
Burcu

**Comment by zhongw2** [comment]
Hi Burcu,

We suggest that you go to the following website: 

https://metazoa.ensembl.org/info/website/ftp/index.html  

1. Input "mellifera" in the search box
2. DNA fasta genome sequence and GTF annotation would be downloaded for our pipeline.

Wenyan
