### ISSUE TITLE
issue met in geneTEFlow installation！

### ISSUE THREAD

**Issue by meng-hhh** [zhongw2/GeneTEFlow#5]
Prof. Zhong
When I installed GeneTEflow , I met  those warnings  showed in picture below in the steps 3  in which commands, " sudo docker build -t rnaseq_pipeline.app .  ", was execute.  How to fix this kind of problems?

my Docker version 18.03.1-ce, build 9ee9f40 in ubuntu 16.04

![image](https://user-images.githubusercontent.com/90771748/133436480-283775d9-24b5-4fe0-8cec-676c2badf66e.png)

**Comment by meng-hhh** [comment]
The problem remains after I upgrade my OS to ubuntu 18.04

**Comment by Davidxcliu** [comment]
Hi,

Please try the solution for this issue here:
https://github.com/zhongw2/GeneTEFlow/issues/3.

Thank you!

**Comment by meng-hhh** [comment]
Thank you!
I got the solution. However I failed to build docker images several times, might due to my first trial of docker.
Meng




***@***.***
 
发件人： Davidxcliu
发送时间： 2021-09-17 11:00
收件人： zhongw2/GeneTEFlow
抄送： meng-hhh; Author
主题： Re: [zhongw2/GeneTEFlow] issue met in geneTEFlow installation！ (#5)
Hi,
Please try the solution for this issue here:
#3.
Thank you!
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by meng-hhh** [comment]
HI:
Thank you for responses!
It's my first trial to use tools in docker, too many difficults!
Could you please provide a step-by-step tutorial for the installation, or provide a image in ducker hub that can be use directly.
Best regards!
Meng



***@***.***
 
发件人： Davidxcliu
发送时间： 2021-09-17 11:00
收件人： zhongw2/GeneTEFlow
抄送： meng-hhh; Author
主题： Re: [zhongw2/GeneTEFlow] issue met in geneTEFlow installation！ (#5)
Closed #5.
―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Davidxcliu** [comment]
Hi Meng,

For docker step-by-step installation, please refer its website: https://docs.docker.com/get-docker/. 
I would suggest that you should test your docker installed functioning well. Then you could follow our tutorial here (https://github.com/zhongw2/GeneTEFlow#2-installation) to install our geneTEFlow in your docker. Our tool installation was fully tested under Ubuntu v16.04, v18.04 and v20.04. 
Also, it would be easier to debug when you try to install one Conda command line in your Dockerfile and build separated docker images for those Conda command lines.

It is a good idea to build a image in docker hub. Maybe we will think about it in the future.

Thank you for being interested in our tool!
